//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.13 at 07:58:15 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iec.ch/61850/2003/SCL", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ch.iec._61850._2003.scl;
