//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.13 at 07:58:15 PM MSK 
//


package ch.iec._61850._2003.scl;

import org.jvnet.jaxb2_commons.lang.*;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for tCommunication complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tCommunication">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tUnNaming">
 *       &lt;sequence>
 *         &lt;element name="SubNetwork" type="{http://www.iec.ch/61850/2003/SCL}tSubNetwork" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCommunication", propOrder = {
    "subNetwork"
})
@Entity(name = "TCommunication")
@Table(name = "TCOMMUNICATION")
public class TCommunication
    extends TUnNaming
    implements Equals, HashCode
{

    @XmlElement(name = "SubNetwork", required = true)
    protected List<TSubNetwork> subNetwork;

    /**
     * Gets the value of the subNetwork property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subNetwork property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubNetwork().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSubNetwork }
     * 
     * 
     */
    @OneToMany(targetEntity = TSubNetwork.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SUB_NETWORK_TCOMMUNICATION_H_0")
    public List<TSubNetwork> getSubNetwork() {
        if (subNetwork == null) {
            subNetwork = new ArrayList<TSubNetwork>();
        }
        return this.subNetwork;
    }

    /**
     * 
     * 
     */
    public void setSubNetwork(List<TSubNetwork> subNetwork) {
        this.subNetwork = subNetwork;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TCommunication)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TCommunication that = ((TCommunication) object);
        {
            List<TSubNetwork> lhsSubNetwork;
            lhsSubNetwork = (((this.subNetwork!= null)&&(!this.subNetwork.isEmpty()))?this.getSubNetwork():null);
            List<TSubNetwork> rhsSubNetwork;
            rhsSubNetwork = (((that.subNetwork!= null)&&(!that.subNetwork.isEmpty()))?that.getSubNetwork():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "subNetwork", lhsSubNetwork), LocatorUtils.property(thatLocator, "subNetwork", rhsSubNetwork), lhsSubNetwork, rhsSubNetwork)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<TSubNetwork> theSubNetwork;
            theSubNetwork = (((this.subNetwork!= null)&&(!this.subNetwork.isEmpty()))?this.getSubNetwork():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "subNetwork", theSubNetwork), currentHashCode, theSubNetwork);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
