//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.13 at 07:58:15 PM MSK 
//


package ch.iec._61850._2003.scl;

import org.jvnet.hyperjaxb3.item.Item;
import org.jvnet.hyperjaxb3.item.ItemUtils;
import org.jvnet.jaxb2_commons.lang.*;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for tControlWithIEDName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tControlWithIEDName">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tControl">
 *       &lt;sequence>
 *         &lt;element name="IEDName" type="{http://www.iec.ch/61850/2003/SCL}tName" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="confRev" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tControlWithIEDName", propOrder = {
    "iedName"
})
@XmlSeeAlso({
    TGSEControl.class,
    TSampledValueControl.class
})
@Entity(name = "TControlWithIEDName")
@Table(name = "TCONTROL_WITH_IEDNAME")
public class TControlWithIEDName
    extends TControl
    implements Equals, HashCode
{

    @XmlElement(name = "IEDName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected List<String> iedName;
    @XmlAttribute(name = "confRev")
    @XmlSchemaType(name = "unsignedInt")
    protected Long confRev;
    protected transient List<TControlWithIEDNameIEDNameItem> iedNameItems;

    /**
     * Gets the value of the iedName property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iedName property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIEDName().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    @Transient
    public List<String> getIEDName() {
        if (iedName == null) {
            iedName = new ArrayList<String>();
        }
        return this.iedName;
    }

    /**
     *
     *
     */
    public void setIEDName(List<String> iedName) {
        this.iedName = iedName;
    }

    /**
     * Gets the value of the confRev property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    @Basic
    @Column(name = "CONF_REV", precision = 10, scale = 0)
    public Long getConfRev() {
        return confRev;
    }

    /**
     * Sets the value of the confRev property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setConfRev(Long value) {
        this.confRev = value;
    }

    @OneToMany(targetEntity = TControlWithIEDName.TControlWithIEDNameIEDNameItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "IEDNAME_ITEMS_TCONTROL_WITH__0")
    public List<TControlWithIEDNameIEDNameItem> getIEDNameItems() {
        if (this.iedNameItems == null) {
            this.iedNameItems = new ArrayList<TControlWithIEDNameIEDNameItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.iedName)) {
            this.iedName = ItemUtils.wrap(this.iedName, this.iedNameItems, TControlWithIEDName.TControlWithIEDNameIEDNameItem.class);
        }
        return this.iedNameItems;
    }

    public void setIEDNameItems(List<TControlWithIEDNameIEDNameItem> value) {
        this.iedName = null;
        this.iedNameItems = null;
        this.iedNameItems = value;
        if (this.iedNameItems == null) {
            this.iedNameItems = new ArrayList<TControlWithIEDNameIEDNameItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.iedName)) {
            this.iedName = ItemUtils.wrap(this.iedName, this.iedNameItems, TControlWithIEDName.TControlWithIEDNameIEDNameItem.class);
        }
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TControlWithIEDName)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TControlWithIEDName that = ((TControlWithIEDName) object);
        {
            List<String> lhsIEDName;
            lhsIEDName = (((this.iedName!= null)&&(!this.iedName.isEmpty()))?this.getIEDName():null);
            List<String> rhsIEDName;
            rhsIEDName = (((that.iedName!= null)&&(!that.iedName.isEmpty()))?that.getIEDName():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "iedName", lhsIEDName), LocatorUtils.property(thatLocator, "iedName", rhsIEDName), lhsIEDName, rhsIEDName)) {
                return false;
            }
        }
        {
            Long lhsConfRev;
            lhsConfRev = this.getConfRev();
            Long rhsConfRev;
            rhsConfRev = that.getConfRev();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "confRev", lhsConfRev), LocatorUtils.property(thatLocator, "confRev", rhsConfRev), lhsConfRev, rhsConfRev)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<String> theIEDName;
            theIEDName = (((this.iedName!= null)&&(!this.iedName.isEmpty()))?this.getIEDName():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "iedName", theIEDName), currentHashCode, theIEDName);
        }
        {
            Long theConfRev;
            theConfRev = this.getConfRev();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "confRev", theConfRev), currentHashCode, theConfRev);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @Entity(name = "TControlWithIEDName$TControlWithIEDNameIEDNameItem")
    @Table(name = "TCONTROL_WITH_IEDNAME_IEDNAM_0")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class TControlWithIEDNameIEDNameItem
        implements Item<String>
    {

        @XmlElement(name = "IEDName", namespace = "http://www.iec.ch/61850/2003/SCL")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String item;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "ITEM", length = 255)
        public String getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItem(String value) {
            this.item = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

    }

}
