//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.13 at 07:58:15 PM MSK 
//


package ch.iec._61850._2003.scl;

import org.jvnet.jaxb2_commons.lang.*;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for tEquipment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tEquipment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tPowerSystemResource">
 *       &lt;attGroup ref="{http://www.iec.ch/61850/2003/SCL}agVirtual"/>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEquipment")
@XmlSeeAlso({
    TGeneralEquipment.class,
    TPowerTransformer.class,
    TAbstractConductingEquipment.class
})
@Entity(name = "TEquipment")
@Table(name = "TEQUIPMENT")
public abstract class TEquipment
    extends TPowerSystemResource
    implements Equals, HashCode
{

    @XmlAttribute(name = "virtual")
    protected Boolean virtual;

    /**
     * Gets the value of the virtual property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Basic
    @Column(name = "VIRTUAL")
    public boolean isVirtual() {
        if (virtual == null) {
            return false;
        } else {
            return virtual;
        }
    }

    /**
     * Sets the value of the virtual property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVirtual(Boolean value) {
        this.virtual = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TEquipment)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TEquipment that = ((TEquipment) object);
        {
            boolean lhsVirtual;
            lhsVirtual = ((this.virtual!= null)?this.isVirtual():false);
            boolean rhsVirtual;
            rhsVirtual = ((that.virtual!= null)?that.isVirtual():false);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "virtual", lhsVirtual), LocatorUtils.property(thatLocator, "virtual", rhsVirtual), lhsVirtual, rhsVirtual)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            boolean theVirtual;
            theVirtual = ((this.virtual!= null)?this.isVirtual():false);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "virtual", theVirtual), currentHashCode, theVirtual);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
