//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.13 at 07:58:15 PM MSK 
//


package ch.iec._61850._2003.scl;

import org.jvnet.hyperjaxb3.item.Item;
import org.jvnet.hyperjaxb3.item.ItemUtils;
import org.jvnet.jaxb2_commons.lang.*;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for tLNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tLNode">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tUnNaming">
 *       &lt;attribute name="lnInst" type="{http://www.iec.ch/61850/2003/SCL}tAnyName" default="" />
 *       &lt;attribute name="lnClass" use="required" type="{http://www.iec.ch/61850/2003/SCL}tLNClassEnum" />
 *       &lt;attribute name="iedName" type="{http://www.iec.ch/61850/2003/SCL}tName" default="None" />
 *       &lt;attribute name="ldInst" type="{http://www.iec.ch/61850/2003/SCL}tAnyName" default="" />
 *       &lt;attribute name="prefix" type="{http://www.iec.ch/61850/2003/SCL}tAnyName" default="" />
 *       &lt;attribute name="lnType" type="{http://www.iec.ch/61850/2003/SCL}tName" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tLNode")
@Entity(name = "TLNode")
@Table(name = "TLNODE")
public class TLNode
    extends TUnNaming
    implements Equals, HashCode
{

    @XmlAttribute(name = "lnInst")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lnInst;
    @XmlAttribute(required = true)
    protected List<String> lnClass;
    @XmlAttribute(name = "iedName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String iedName;
    @XmlAttribute(name = "ldInst")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ldInst;
    @XmlAttribute(name = "prefix")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String prefix;
    @XmlAttribute(name = "lnType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lnType;
    protected transient List<TLNodeLnClassItem> lnClassItems;

    /**
     * Gets the value of the lnInst property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Basic
    @Column(name = "LN_INST", length = 255)
    public String getLnInst() {
        if (lnInst == null) {
            return "";
        } else {
            return lnInst;
        }
    }

    /**
     * Sets the value of the lnInst property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLnInst(String value) {
        this.lnInst = value;
    }

    /**
     * Gets the value of the lnClass property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lnClass property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLnClass().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    @Transient
    public List<String> getLnClass() {
        if (lnClass == null) {
            lnClass = new ArrayList<String>();
        }
        return this.lnClass;
    }

    /**
     *
     *
     */
    public void setLnClass(List<String> lnClass) {
        this.lnClass = lnClass;
    }

    /**
     * Gets the value of the iedName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Basic
    @Column(name = "IED_NAME", length = 255)
    public String getIedName() {
        if (iedName == null) {
            return "None";
        } else {
            return iedName;
        }
    }

    /**
     * Sets the value of the iedName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIedName(String value) {
        this.iedName = value;
    }

    /**
     * Gets the value of the ldInst property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Basic
    @Column(name = "LD_INST", length = 255)
    public String getLdInst() {
        if (ldInst == null) {
            return "";
        } else {
            return ldInst;
        }
    }

    /**
     * Sets the value of the ldInst property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLdInst(String value) {
        this.ldInst = value;
    }

    /**
     * Gets the value of the prefix property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Basic
    @Column(name = "PREFIX_", length = 255)
    public String getPrefix() {
        if (prefix == null) {
            return "";
        } else {
            return prefix;
        }
    }

    /**
     * Sets the value of the prefix property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the lnType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Basic
    @Column(name = "LN_TYPE", length = 255)
    public String getLnType() {
        return lnType;
    }

    /**
     * Sets the value of the lnType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLnType(String value) {
        this.lnType = value;
    }

    @OneToMany(targetEntity = TLNode.TLNodeLnClassItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "LN_CLASS_ITEMS_TLNODE_HJID")
    public List<TLNodeLnClassItem> getLnClassItems() {
        if (this.lnClassItems == null) {
            this.lnClassItems = new ArrayList<TLNodeLnClassItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.lnClass)) {
            this.lnClass = ItemUtils.wrap(this.lnClass, this.lnClassItems, TLNode.TLNodeLnClassItem.class);
        }
        return this.lnClassItems;
    }

    public void setLnClassItems(List<TLNodeLnClassItem> value) {
        this.lnClass = null;
        this.lnClassItems = null;
        this.lnClassItems = value;
        if (this.lnClassItems == null) {
            this.lnClassItems = new ArrayList<TLNodeLnClassItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.lnClass)) {
            this.lnClass = ItemUtils.wrap(this.lnClass, this.lnClassItems, TLNode.TLNodeLnClassItem.class);
        }
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TLNode)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TLNode that = ((TLNode) object);
        {
            String lhsLnInst;
            lhsLnInst = this.getLnInst();
            String rhsLnInst;
            rhsLnInst = that.getLnInst();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "lnInst", lhsLnInst), LocatorUtils.property(thatLocator, "lnInst", rhsLnInst), lhsLnInst, rhsLnInst)) {
                return false;
            }
        }
        {
            List<String> lhsLnClass;
            lhsLnClass = (((this.lnClass!= null)&&(!this.lnClass.isEmpty()))?this.getLnClass():null);
            List<String> rhsLnClass;
            rhsLnClass = (((that.lnClass!= null)&&(!that.lnClass.isEmpty()))?that.getLnClass():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "lnClass", lhsLnClass), LocatorUtils.property(thatLocator, "lnClass", rhsLnClass), lhsLnClass, rhsLnClass)) {
                return false;
            }
        }
        {
            String lhsIedName;
            lhsIedName = this.getIedName();
            String rhsIedName;
            rhsIedName = that.getIedName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "iedName", lhsIedName), LocatorUtils.property(thatLocator, "iedName", rhsIedName), lhsIedName, rhsIedName)) {
                return false;
            }
        }
        {
            String lhsLdInst;
            lhsLdInst = this.getLdInst();
            String rhsLdInst;
            rhsLdInst = that.getLdInst();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ldInst", lhsLdInst), LocatorUtils.property(thatLocator, "ldInst", rhsLdInst), lhsLdInst, rhsLdInst)) {
                return false;
            }
        }
        {
            String lhsPrefix;
            lhsPrefix = this.getPrefix();
            String rhsPrefix;
            rhsPrefix = that.getPrefix();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "prefix", lhsPrefix), LocatorUtils.property(thatLocator, "prefix", rhsPrefix), lhsPrefix, rhsPrefix)) {
                return false;
            }
        }
        {
            String lhsLnType;
            lhsLnType = this.getLnType();
            String rhsLnType;
            rhsLnType = that.getLnType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "lnType", lhsLnType), LocatorUtils.property(thatLocator, "lnType", rhsLnType), lhsLnType, rhsLnType)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            String theLnInst;
            theLnInst = this.getLnInst();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "lnInst", theLnInst), currentHashCode, theLnInst);
        }
        {
            List<String> theLnClass;
            theLnClass = (((this.lnClass!= null)&&(!this.lnClass.isEmpty()))?this.getLnClass():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "lnClass", theLnClass), currentHashCode, theLnClass);
        }
        {
            String theIedName;
            theIedName = this.getIedName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "iedName", theIedName), currentHashCode, theIedName);
        }
        {
            String theLdInst;
            theLdInst = this.getLdInst();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ldInst", theLdInst), currentHashCode, theLdInst);
        }
        {
            String thePrefix;
            thePrefix = this.getPrefix();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "prefix", thePrefix), currentHashCode, thePrefix);
        }
        {
            String theLnType;
            theLnType = this.getLnType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "lnType", theLnType), currentHashCode, theLnType);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @Entity(name = "TLNode$TLNodeLnClassItem")
    @Table(name = "TLNODE_LN_CLASS_ITEM")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class TLNodeLnClassItem
        implements Item<String>
    {

        @XmlElement(name = "LnClass")
        protected String item;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "ITEM")
        public String getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItem(String value) {
            this.item = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

    }

}
