//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.13 at 07:58:15 PM MSK 
//


package ch.iec._61850._2003.scl;

import org.jvnet.jaxb2_commons.lang.*;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tReportControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tReportControl">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tControlWithTriggerOpt">
 *       &lt;sequence>
 *         &lt;element name="OptFields">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attGroup ref="{http://www.iec.ch/61850/2003/SCL}agOptFields"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RptEnabled" type="{http://www.iec.ch/61850/2003/SCL}tRptEnabled" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rptID" type="{http://www.iec.ch/61850/2003/SCL}tAnyName" />
 *       &lt;attribute name="confRev" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="buffered" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="bufTime" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tReportControl", propOrder = {
    "optFields",
    "rptEnabled"
})
@Entity(name = "TReportControl")
@Table(name = "TREPORT_CONTROL")
public class TReportControl
    extends TControlWithTriggerOpt
    implements Equals, HashCode
{

    @XmlElement(name = "OptFields", required = true)
    protected TReportControl.OptFields optFields;
    @XmlElement(name = "RptEnabled")
    protected TRptEnabled rptEnabled;
    @XmlAttribute(name = "rptID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rptID;
    @XmlAttribute(name = "confRev", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long confRev;
    @XmlAttribute(name = "buffered")
    protected Boolean buffered;
    @XmlAttribute(name = "bufTime")
    @XmlSchemaType(name = "unsignedInt")
    protected Long bufTime;

    /**
     * Gets the value of the optFields property.
     *
     * @return
     *     possible object is
     *     {@link TReportControl.OptFields }
     *
     */
    @ManyToOne(targetEntity = TReportControl.OptFields.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "OPT_FIELDS_TREPORT_CONTROL_H_0")
    public TReportControl.OptFields getOptFields() {
        return optFields;
    }

    /**
     * Sets the value of the optFields property.
     *
     * @param value
     *     allowed object is
     *     {@link TReportControl.OptFields }
     *
     */
    public void setOptFields(TReportControl.OptFields value) {
        this.optFields = value;
    }

    /**
     * Gets the value of the rptEnabled property.
     *
     * @return
     *     possible object is
     *     {@link TRptEnabled }
     *
     */
    @ManyToOne(targetEntity = TRptEnabled.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "RPT_ENABLED_TREPORT_CONTROL__0")
    public TRptEnabled getRptEnabled() {
        return rptEnabled;
    }

    /**
     * Sets the value of the rptEnabled property.
     *
     * @param value
     *     allowed object is
     *     {@link TRptEnabled }
     *
     */
    public void setRptEnabled(TRptEnabled value) {
        this.rptEnabled = value;
    }

    /**
     * Gets the value of the rptID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Basic
    @Column(name = "RPT_ID", length = 255)
    public String getRptID() {
        return rptID;
    }

    /**
     * Sets the value of the rptID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRptID(String value) {
        this.rptID = value;
    }

    /**
     * Gets the value of the confRev property.
     *
     */
    @Basic
    @Column(name = "CONF_REV", precision = 10, scale = 0)
    public long getConfRev() {
        return confRev;
    }

    /**
     * Sets the value of the confRev property.
     *
     */
    public void setConfRev(long value) {
        this.confRev = value;
    }

    /**
     * Gets the value of the buffered property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    @Basic
    @Column(name = "BUFFERED")
    public boolean isBuffered() {
        if (buffered == null) {
            return false;
        } else {
            return buffered;
        }
    }

    /**
     * Sets the value of the buffered property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setBuffered(Boolean value) {
        this.buffered = value;
    }

    /**
     * Gets the value of the bufTime property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    @Basic
    @Column(name = "BUF_TIME", precision = 10, scale = 0)
    public long getBufTime() {
        if (bufTime == null) {
            return  0L;
        } else {
            return bufTime;
        }
    }

    /**
     * Sets the value of the bufTime property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setBufTime(Long value) {
        this.bufTime = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TReportControl)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TReportControl that = ((TReportControl) object);
        {
            TReportControl.OptFields lhsOptFields;
            lhsOptFields = this.getOptFields();
            TReportControl.OptFields rhsOptFields;
            rhsOptFields = that.getOptFields();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "optFields", lhsOptFields), LocatorUtils.property(thatLocator, "optFields", rhsOptFields), lhsOptFields, rhsOptFields)) {
                return false;
            }
        }
        {
            TRptEnabled lhsRptEnabled;
            lhsRptEnabled = this.getRptEnabled();
            TRptEnabled rhsRptEnabled;
            rhsRptEnabled = that.getRptEnabled();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "rptEnabled", lhsRptEnabled), LocatorUtils.property(thatLocator, "rptEnabled", rhsRptEnabled), lhsRptEnabled, rhsRptEnabled)) {
                return false;
            }
        }
        {
            String lhsRptID;
            lhsRptID = this.getRptID();
            String rhsRptID;
            rhsRptID = that.getRptID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "rptID", lhsRptID), LocatorUtils.property(thatLocator, "rptID", rhsRptID), lhsRptID, rhsRptID)) {
                return false;
            }
        }
        {
            long lhsConfRev;
            lhsConfRev = this.getConfRev();
            long rhsConfRev;
            rhsConfRev = that.getConfRev();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "confRev", lhsConfRev), LocatorUtils.property(thatLocator, "confRev", rhsConfRev), lhsConfRev, rhsConfRev)) {
                return false;
            }
        }
        {
            boolean lhsBuffered;
            lhsBuffered = ((this.buffered!= null)?this.isBuffered():false);
            boolean rhsBuffered;
            rhsBuffered = ((that.buffered!= null)?that.isBuffered():false);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "buffered", lhsBuffered), LocatorUtils.property(thatLocator, "buffered", rhsBuffered), lhsBuffered, rhsBuffered)) {
                return false;
            }
        }
        {
            long lhsBufTime;
            lhsBufTime = ((this.bufTime!= null)?this.getBufTime(): 0L);
            long rhsBufTime;
            rhsBufTime = ((that.bufTime!= null)?that.getBufTime(): 0L);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "bufTime", lhsBufTime), LocatorUtils.property(thatLocator, "bufTime", rhsBufTime), lhsBufTime, rhsBufTime)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            TReportControl.OptFields theOptFields;
            theOptFields = this.getOptFields();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "optFields", theOptFields), currentHashCode, theOptFields);
        }
        {
            TRptEnabled theRptEnabled;
            theRptEnabled = this.getRptEnabled();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "rptEnabled", theRptEnabled), currentHashCode, theRptEnabled);
        }
        {
            String theRptID;
            theRptID = this.getRptID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "rptID", theRptID), currentHashCode, theRptID);
        }
        {
            long theConfRev;
            theConfRev = this.getConfRev();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "confRev", theConfRev), currentHashCode, theConfRev);
        }
        {
            boolean theBuffered;
            theBuffered = ((this.buffered!= null)?this.isBuffered():false);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "buffered", theBuffered), currentHashCode, theBuffered);
        }
        {
            long theBufTime;
            theBufTime = ((this.bufTime!= null)?this.getBufTime(): 0L);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "bufTime", theBufTime), currentHashCode, theBufTime);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attGroup ref="{http://www.iec.ch/61850/2003/SCL}agOptFields"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    @Entity(name = "TReportControl$OptFields")
    @Table(name = "OPT_FIELDS")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class OptFields
        implements Equals, HashCode
    {

        @XmlAttribute(name = "seqNum")
        protected Boolean seqNum;
        @XmlAttribute(name = "timeStamp")
        protected Boolean timeStamp;
        @XmlAttribute(name = "dataSet")
        protected Boolean dataSet;
        @XmlAttribute(name = "reasonCode")
        protected Boolean reasonCode;
        @XmlAttribute(name = "dataRef")
        protected Boolean dataRef;
        @XmlAttribute(name = "entryID")
        protected Boolean entryID;
        @XmlAttribute(name = "configRef")
        protected Boolean configRef;
        @XmlAttribute(name = "bufOvfl")
        protected Boolean bufOvfl;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * Gets the value of the seqNum property.
         *
         * @return
         *     possible object is
         *     {@link Boolean }
         *
         */
        @Basic
        @Column(name = "SEQ_NUM")
        public boolean isSeqNum() {
            if (seqNum == null) {
                return false;
            } else {
                return seqNum;
            }
        }

        /**
         * Sets the value of the seqNum property.
         *
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *
         */
        public void setSeqNum(Boolean value) {
            this.seqNum = value;
        }

        /**
         * Gets the value of the timeStamp property.
         *
         * @return
         *     possible object is
         *     {@link Boolean }
         *
         */
        @Basic
        @Column(name = "TIME_STAMP")
        public boolean isTimeStamp() {
            if (timeStamp == null) {
                return false;
            } else {
                return timeStamp;
            }
        }

        /**
         * Sets the value of the timeStamp property.
         *
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *
         */
        public void setTimeStamp(Boolean value) {
            this.timeStamp = value;
        }

        /**
         * Gets the value of the dataSet property.
         *
         * @return
         *     possible object is
         *     {@link Boolean }
         *
         */
        @Basic
        @Column(name = "DATA_SET")
        public boolean isDataSet() {
            if (dataSet == null) {
                return false;
            } else {
                return dataSet;
            }
        }

        /**
         * Sets the value of the dataSet property.
         *
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *
         */
        public void setDataSet(Boolean value) {
            this.dataSet = value;
        }

        /**
         * Gets the value of the reasonCode property.
         *
         * @return
         *     possible object is
         *     {@link Boolean }
         *
         */
        @Basic
        @Column(name = "REASON_CODE")
        public boolean isReasonCode() {
            if (reasonCode == null) {
                return false;
            } else {
                return reasonCode;
            }
        }

        /**
         * Sets the value of the reasonCode property.
         *
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *
         */
        public void setReasonCode(Boolean value) {
            this.reasonCode = value;
        }

        /**
         * Gets the value of the dataRef property.
         *
         * @return
         *     possible object is
         *     {@link Boolean }
         *
         */
        @Basic
        @Column(name = "DATA_REF")
        public boolean isDataRef() {
            if (dataRef == null) {
                return false;
            } else {
                return dataRef;
            }
        }

        /**
         * Sets the value of the dataRef property.
         *
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *
         */
        public void setDataRef(Boolean value) {
            this.dataRef = value;
        }

        /**
         * Gets the value of the entryID property.
         *
         * @return
         *     possible object is
         *     {@link Boolean }
         *
         */
        @Basic
        @Column(name = "ENTRY_ID")
        public boolean isEntryID() {
            if (entryID == null) {
                return false;
            } else {
                return entryID;
            }
        }

        /**
         * Sets the value of the entryID property.
         *
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *
         */
        public void setEntryID(Boolean value) {
            this.entryID = value;
        }

        /**
         * Gets the value of the configRef property.
         *
         * @return
         *     possible object is
         *     {@link Boolean }
         *
         */
        @Basic
        @Column(name = "CONFIG_REF")
        public boolean isConfigRef() {
            if (configRef == null) {
                return false;
            } else {
                return configRef;
            }
        }

        /**
         * Sets the value of the configRef property.
         *
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *
         */
        public void setConfigRef(Boolean value) {
            this.configRef = value;
        }

        /**
         * Gets the value of the bufOvfl property.
         *
         * @return
         *     possible object is
         *     {@link Boolean }
         *
         */
        @Basic
        @Column(name = "BUF_OVFL")
        public boolean isBufOvfl() {
            if (bufOvfl == null) {
                return true;
            } else {
                return bufOvfl;
            }
        }

        /**
         * Sets the value of the bufOvfl property.
         *
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *
         */
        public void setBufOvfl(Boolean value) {
            this.bufOvfl = value;
        }

        /**
         * Gets the value of the hjid property.
         *
         * @return
         *     possible object is
         *     {@link Long }
         *
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         *
         * @param value
         *     allowed object is
         *     {@link Long }
         *
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof TReportControl.OptFields)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final TReportControl.OptFields that = ((TReportControl.OptFields) object);
            {
                boolean lhsSeqNum;
                lhsSeqNum = ((this.seqNum!= null)?this.isSeqNum():false);
                boolean rhsSeqNum;
                rhsSeqNum = ((that.seqNum!= null)?that.isSeqNum():false);
                if (!strategy.equals(LocatorUtils.property(thisLocator, "seqNum", lhsSeqNum), LocatorUtils.property(thatLocator, "seqNum", rhsSeqNum), lhsSeqNum, rhsSeqNum)) {
                    return false;
                }
            }
            {
                boolean lhsTimeStamp;
                lhsTimeStamp = ((this.timeStamp!= null)?this.isTimeStamp():false);
                boolean rhsTimeStamp;
                rhsTimeStamp = ((that.timeStamp!= null)?that.isTimeStamp():false);
                if (!strategy.equals(LocatorUtils.property(thisLocator, "timeStamp", lhsTimeStamp), LocatorUtils.property(thatLocator, "timeStamp", rhsTimeStamp), lhsTimeStamp, rhsTimeStamp)) {
                    return false;
                }
            }
            {
                boolean lhsDataSet;
                lhsDataSet = ((this.dataSet!= null)?this.isDataSet():false);
                boolean rhsDataSet;
                rhsDataSet = ((that.dataSet!= null)?that.isDataSet():false);
                if (!strategy.equals(LocatorUtils.property(thisLocator, "dataSet", lhsDataSet), LocatorUtils.property(thatLocator, "dataSet", rhsDataSet), lhsDataSet, rhsDataSet)) {
                    return false;
                }
            }
            {
                boolean lhsReasonCode;
                lhsReasonCode = ((this.reasonCode!= null)?this.isReasonCode():false);
                boolean rhsReasonCode;
                rhsReasonCode = ((that.reasonCode!= null)?that.isReasonCode():false);
                if (!strategy.equals(LocatorUtils.property(thisLocator, "reasonCode", lhsReasonCode), LocatorUtils.property(thatLocator, "reasonCode", rhsReasonCode), lhsReasonCode, rhsReasonCode)) {
                    return false;
                }
            }
            {
                boolean lhsDataRef;
                lhsDataRef = ((this.dataRef!= null)?this.isDataRef():false);
                boolean rhsDataRef;
                rhsDataRef = ((that.dataRef!= null)?that.isDataRef():false);
                if (!strategy.equals(LocatorUtils.property(thisLocator, "dataRef", lhsDataRef), LocatorUtils.property(thatLocator, "dataRef", rhsDataRef), lhsDataRef, rhsDataRef)) {
                    return false;
                }
            }
            {
                boolean lhsEntryID;
                lhsEntryID = ((this.entryID!= null)?this.isEntryID():false);
                boolean rhsEntryID;
                rhsEntryID = ((that.entryID!= null)?that.isEntryID():false);
                if (!strategy.equals(LocatorUtils.property(thisLocator, "entryID", lhsEntryID), LocatorUtils.property(thatLocator, "entryID", rhsEntryID), lhsEntryID, rhsEntryID)) {
                    return false;
                }
            }
            {
                boolean lhsConfigRef;
                lhsConfigRef = ((this.configRef!= null)?this.isConfigRef():false);
                boolean rhsConfigRef;
                rhsConfigRef = ((that.configRef!= null)?that.isConfigRef():false);
                if (!strategy.equals(LocatorUtils.property(thisLocator, "configRef", lhsConfigRef), LocatorUtils.property(thatLocator, "configRef", rhsConfigRef), lhsConfigRef, rhsConfigRef)) {
                    return false;
                }
            }
            {
                boolean lhsBufOvfl;
                lhsBufOvfl = ((this.bufOvfl!= null)?this.isBufOvfl():false);
                boolean rhsBufOvfl;
                rhsBufOvfl = ((that.bufOvfl!= null)?that.isBufOvfl():false);
                if (!strategy.equals(LocatorUtils.property(thisLocator, "bufOvfl", lhsBufOvfl), LocatorUtils.property(thatLocator, "bufOvfl", rhsBufOvfl), lhsBufOvfl, rhsBufOvfl)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = 1;
            {
                boolean theSeqNum;
                theSeqNum = ((this.seqNum!= null)?this.isSeqNum():false);
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "seqNum", theSeqNum), currentHashCode, theSeqNum);
            }
            {
                boolean theTimeStamp;
                theTimeStamp = ((this.timeStamp!= null)?this.isTimeStamp():false);
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "timeStamp", theTimeStamp), currentHashCode, theTimeStamp);
            }
            {
                boolean theDataSet;
                theDataSet = ((this.dataSet!= null)?this.isDataSet():false);
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "dataSet", theDataSet), currentHashCode, theDataSet);
            }
            {
                boolean theReasonCode;
                theReasonCode = ((this.reasonCode!= null)?this.isReasonCode():false);
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "reasonCode", theReasonCode), currentHashCode, theReasonCode);
            }
            {
                boolean theDataRef;
                theDataRef = ((this.dataRef!= null)?this.isDataRef():false);
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "dataRef", theDataRef), currentHashCode, theDataRef);
            }
            {
                boolean theEntryID;
                theEntryID = ((this.entryID!= null)?this.isEntryID():false);
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "entryID", theEntryID), currentHashCode, theEntryID);
            }
            {
                boolean theConfigRef;
                theConfigRef = ((this.configRef!= null)?this.isConfigRef():false);
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "configRef", theConfigRef), currentHashCode, theConfigRef);
            }
            {
                boolean theBufOvfl;
                theBufOvfl = ((this.bufOvfl!= null)?this.isBufOvfl():false);
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "bufOvfl", theBufOvfl), currentHashCode, theBufOvfl);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

    }

}
