//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.13 at 07:58:15 PM MSK 
//


package ch.iec._61850._2003.scl;

import org.jvnet.jaxb2_commons.lang.*;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for tRptEnabled complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tRptEnabled">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tUnNaming">
 *       &lt;sequence>
 *         &lt;element name="ClientLN" type="{http://www.iec.ch/61850/2003/SCL}tClientLN" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="1" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tRptEnabled", propOrder = {
    "clientLN"
})
@Entity(name = "TRptEnabled")
@Table(name = "TRPT_ENABLED")
public class TRptEnabled
    extends TUnNaming
    implements Equals, HashCode
{

    @XmlElement(name = "ClientLN")
    protected List<TClientLN> clientLN;
    @XmlAttribute(name = "max")
    @XmlSchemaType(name = "unsignedInt")
    protected Long max;

    /**
     * Gets the value of the clientLN property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clientLN property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClientLN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TClientLN }
     * 
     * 
     */
    @OneToMany(targetEntity = TClientLN.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "CLIENT_LN_TRPT_ENABLED_HJID")
    public List<TClientLN> getClientLN() {
        if (clientLN == null) {
            clientLN = new ArrayList<TClientLN>();
        }
        return this.clientLN;
    }

    /**
     * 
     * 
     */
    public void setClientLN(List<TClientLN> clientLN) {
        this.clientLN = clientLN;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Basic
    @Column(name = "MAX_", precision = 10, scale = 0)
    public long getMax() {
        if (max == null) {
            return  1L;
        } else {
            return max;
        }
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMax(Long value) {
        this.max = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TRptEnabled)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TRptEnabled that = ((TRptEnabled) object);
        {
            List<TClientLN> lhsClientLN;
            lhsClientLN = (((this.clientLN!= null)&&(!this.clientLN.isEmpty()))?this.getClientLN():null);
            List<TClientLN> rhsClientLN;
            rhsClientLN = (((that.clientLN!= null)&&(!that.clientLN.isEmpty()))?that.getClientLN():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "clientLN", lhsClientLN), LocatorUtils.property(thatLocator, "clientLN", rhsClientLN), lhsClientLN, rhsClientLN)) {
                return false;
            }
        }
        {
            long lhsMax;
            lhsMax = ((this.max!= null)?this.getMax(): 0L);
            long rhsMax;
            rhsMax = ((that.max!= null)?that.getMax(): 0L);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "max", lhsMax), LocatorUtils.property(thatLocator, "max", rhsMax), lhsMax, rhsMax)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<TClientLN> theClientLN;
            theClientLN = (((this.clientLN!= null)&&(!this.clientLN.isEmpty()))?this.getClientLN():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "clientLN", theClientLN), currentHashCode, theClientLN);
        }
        {
            long theMax;
            theMax = ((this.max!= null)?this.getMax(): 0L);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "max", theMax), currentHashCode, theMax);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
