//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.13 at 07:58:15 PM MSK 
//


package ch.iec._61850._2003.scl;

import org.jvnet.jaxb2_commons.lang.*;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tServiceWithMaxAndMaxAttributesAndModify complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tServiceWithMaxAndMaxAttributesAndModify">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tServiceWithMaxAndMaxAttributes">
 *       &lt;attribute name="modify" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tServiceWithMaxAndMaxAttributesAndModify")
@Entity(name = "TServiceWithMaxAndMaxAttributesAndModify")
@Table(name = "TSERVICE_WITH_MAX_AND_MAX_AT_0")
public class TServiceWithMaxAndMaxAttributesAndModify
    extends TServiceWithMaxAndMaxAttributes
    implements Equals, HashCode
{

    @XmlAttribute(name = "modify")
    protected Boolean modify;

    /**
     * Gets the value of the modify property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Basic
    @Column(name = "MODIFY_")
    public boolean isModify() {
        if (modify == null) {
            return true;
        } else {
            return modify;
        }
    }

    /**
     * Sets the value of the modify property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setModify(Boolean value) {
        this.modify = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TServiceWithMaxAndMaxAttributesAndModify)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TServiceWithMaxAndMaxAttributesAndModify that = ((TServiceWithMaxAndMaxAttributesAndModify) object);
        {
            boolean lhsModify;
            lhsModify = ((this.modify!= null)?this.isModify():false);
            boolean rhsModify;
            rhsModify = ((that.modify!= null)?that.isModify():false);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "modify", lhsModify), LocatorUtils.property(thatLocator, "modify", rhsModify), lhsModify, rhsModify)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            boolean theModify;
            theModify = ((this.modify!= null)?this.isModify():false);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "modify", theModify), currentHashCode, theModify);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
