//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.13 at 07:58:15 PM MSK 
//


package ch.iec._61850._2003.scl;

import org.jvnet.jaxb2_commons.lang.*;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for tSettingControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSettingControl">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tUnNaming">
 *       &lt;attribute name="numOfSGs" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="actSG" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="1" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSettingControl")
@Entity(name = "TSettingControl")
@Table(name = "TSETTING_CONTROL")
public class TSettingControl
    extends TUnNaming
    implements Equals, HashCode
{

    @XmlAttribute(name = "numOfSGs", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long numOfSGs;
    @XmlAttribute(name = "actSG")
    @XmlSchemaType(name = "unsignedInt")
    protected Long actSG;

    /**
     * Gets the value of the numOfSGs property.
     * 
     */
    @Basic
    @Column(name = "NUM_OF_SGS", precision = 10, scale = 0)
    public long getNumOfSGs() {
        return numOfSGs;
    }

    /**
     * Sets the value of the numOfSGs property.
     * 
     */
    public void setNumOfSGs(long value) {
        this.numOfSGs = value;
    }

    /**
     * Gets the value of the actSG property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Basic
    @Column(name = "ACT_SG", precision = 10, scale = 0)
    public long getActSG() {
        if (actSG == null) {
            return  1L;
        } else {
            return actSG;
        }
    }

    /**
     * Sets the value of the actSG property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setActSG(Long value) {
        this.actSG = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TSettingControl)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TSettingControl that = ((TSettingControl) object);
        {
            long lhsNumOfSGs;
            lhsNumOfSGs = this.getNumOfSGs();
            long rhsNumOfSGs;
            rhsNumOfSGs = that.getNumOfSGs();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "numOfSGs", lhsNumOfSGs), LocatorUtils.property(thatLocator, "numOfSGs", rhsNumOfSGs), lhsNumOfSGs, rhsNumOfSGs)) {
                return false;
            }
        }
        {
            long lhsActSG;
            lhsActSG = ((this.actSG!= null)?this.getActSG(): 0L);
            long rhsActSG;
            rhsActSG = ((that.actSG!= null)?that.getActSG(): 0L);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "actSG", lhsActSG), LocatorUtils.property(thatLocator, "actSG", rhsActSG), lhsActSG, rhsActSG)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            long theNumOfSGs;
            theNumOfSGs = this.getNumOfSGs();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "numOfSGs", theNumOfSGs), currentHashCode, theNumOfSGs);
        }
        {
            long theActSG;
            theActSG = ((this.actSG!= null)?this.getActSG(): 0L);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "actSG", theActSG), currentHashCode, theActSG);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
