//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.13 at 07:58:15 PM MSK 
//


package ch.iec._61850._2003.scl;

import org.jvnet.hyperjaxb3.item.Item;
import org.jvnet.hyperjaxb3.item.ItemUtils;
import org.jvnet.jaxb2_commons.lang.*;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for tSMVSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSMVSettings">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tServiceSettings">
 *       &lt;sequence>
 *         &lt;element name="SmpRate" maxOccurs="unbounded">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="svID" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="optFields" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="smpRate" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsEnum" default="Fix" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSMVSettings", propOrder = {
    "smpRate"
})
@Entity(name = "TSMVSettings")
@Table(name = "TSMVSETTINGS")
public class TSMVSettings
    extends TServiceSettings
    implements Equals, HashCode
{

    @XmlElement(name = "SmpRate", required = true)
    protected List<BigDecimal> smpRate;
    @XmlAttribute(name = "svID")
    protected TServiceSettingsEnum svID;
    @XmlAttribute(name = "optFields")
    protected TServiceSettingsEnum optFields;
    @XmlAttribute(name = "smpRate")
    protected TServiceSettingsEnum smpRateAttribute;
    protected transient List<TSMVSettingsSmpRateItem> smpRateItems;

    /**
     * Gets the value of the smpRate property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the smpRate property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSmpRate().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     *
     *
     */
    @Transient
    public List<BigDecimal> getSmpRate() {
        if (smpRate == null) {
            smpRate = new ArrayList<BigDecimal>();
        }
        return this.smpRate;
    }

    /**
     *
     *
     */
    public void setSmpRate(List<BigDecimal> smpRate) {
        this.smpRate = smpRate;
    }

    /**
     * Gets the value of the svID property.
     *
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *
     */
    @Basic
    @Column(name = "SV_ID", length = 255)
    @Enumerated(EnumType.STRING)
    public TServiceSettingsEnum getSvID() {
        if (svID == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return svID;
        }
    }

    /**
     * Sets the value of the svID property.
     *
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *
     */
    public void setSvID(TServiceSettingsEnum value) {
        this.svID = value;
    }

    /**
     * Gets the value of the optFields property.
     *
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *
     */
    @Basic
    @Column(name = "OPT_FIELDS", length = 255)
    @Enumerated(EnumType.STRING)
    public TServiceSettingsEnum getOptFields() {
        if (optFields == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return optFields;
        }
    }

    /**
     * Sets the value of the optFields property.
     *
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *
     */
    public void setOptFields(TServiceSettingsEnum value) {
        this.optFields = value;
    }

    /**
     * Gets the value of the smpRateAttribute property.
     *
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *
     */
    @Basic
    @Column(name = "SMP_RATE_ATTRIBUTE", length = 255)
    @Enumerated(EnumType.STRING)
    public TServiceSettingsEnum getSmpRateAttribute() {
        if (smpRateAttribute == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return smpRateAttribute;
        }
    }

    /**
     * Sets the value of the smpRateAttribute property.
     *
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *
     */
    public void setSmpRateAttribute(TServiceSettingsEnum value) {
        this.smpRateAttribute = value;
    }

    @OneToMany(targetEntity = TSMVSettings.TSMVSettingsSmpRateItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SMP_RATE_ITEMS_TSMVSETTINGS__0")
    public List<TSMVSettingsSmpRateItem> getSmpRateItems() {
        if (this.smpRateItems == null) {
            this.smpRateItems = new ArrayList<TSMVSettingsSmpRateItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.smpRate)) {
            this.smpRate = ItemUtils.wrap(this.smpRate, this.smpRateItems, TSMVSettings.TSMVSettingsSmpRateItem.class);
        }
        return this.smpRateItems;
    }

    public void setSmpRateItems(List<TSMVSettingsSmpRateItem> value) {
        this.smpRate = null;
        this.smpRateItems = null;
        this.smpRateItems = value;
        if (this.smpRateItems == null) {
            this.smpRateItems = new ArrayList<TSMVSettingsSmpRateItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.smpRate)) {
            this.smpRate = ItemUtils.wrap(this.smpRate, this.smpRateItems, TSMVSettings.TSMVSettingsSmpRateItem.class);
        }
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TSMVSettings)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TSMVSettings that = ((TSMVSettings) object);
        {
            List<BigDecimal> lhsSmpRate;
            lhsSmpRate = (((this.smpRate!= null)&&(!this.smpRate.isEmpty()))?this.getSmpRate():null);
            List<BigDecimal> rhsSmpRate;
            rhsSmpRate = (((that.smpRate!= null)&&(!that.smpRate.isEmpty()))?that.getSmpRate():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "smpRate", lhsSmpRate), LocatorUtils.property(thatLocator, "smpRate", rhsSmpRate), lhsSmpRate, rhsSmpRate)) {
                return false;
            }
        }
        {
            TServiceSettingsEnum lhsSvID;
            lhsSvID = this.getSvID();
            TServiceSettingsEnum rhsSvID;
            rhsSvID = that.getSvID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "svID", lhsSvID), LocatorUtils.property(thatLocator, "svID", rhsSvID), lhsSvID, rhsSvID)) {
                return false;
            }
        }
        {
            TServiceSettingsEnum lhsOptFields;
            lhsOptFields = this.getOptFields();
            TServiceSettingsEnum rhsOptFields;
            rhsOptFields = that.getOptFields();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "optFields", lhsOptFields), LocatorUtils.property(thatLocator, "optFields", rhsOptFields), lhsOptFields, rhsOptFields)) {
                return false;
            }
        }
        {
            TServiceSettingsEnum lhsSmpRateAttribute;
            lhsSmpRateAttribute = this.getSmpRateAttribute();
            TServiceSettingsEnum rhsSmpRateAttribute;
            rhsSmpRateAttribute = that.getSmpRateAttribute();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "smpRateAttribute", lhsSmpRateAttribute), LocatorUtils.property(thatLocator, "smpRateAttribute", rhsSmpRateAttribute), lhsSmpRateAttribute, rhsSmpRateAttribute)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<BigDecimal> theSmpRate;
            theSmpRate = (((this.smpRate!= null)&&(!this.smpRate.isEmpty()))?this.getSmpRate():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "smpRate", theSmpRate), currentHashCode, theSmpRate);
        }
        {
            TServiceSettingsEnum theSvID;
            theSvID = this.getSvID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "svID", theSvID), currentHashCode, theSvID);
        }
        {
            TServiceSettingsEnum theOptFields;
            theOptFields = this.getOptFields();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "optFields", theOptFields), currentHashCode, theOptFields);
        }
        {
            TServiceSettingsEnum theSmpRateAttribute;
            theSmpRateAttribute = this.getSmpRateAttribute();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "smpRateAttribute", theSmpRateAttribute), currentHashCode, theSmpRateAttribute);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @Entity(name = "TSMVSettings$TSMVSettingsSmpRateItem")
    @Table(name = "TSMVSETTINGS_SMP_RATE_ITEM")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class TSMVSettingsSmpRateItem
        implements Item<BigDecimal>
    {

        @XmlElement(name = "SmpRate", namespace = "http://www.iec.ch/61850/2003/SCL")
        protected BigDecimal item;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        @Basic
        @Column(name = "ITEM")
        public BigDecimal getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setItem(BigDecimal value) {
            this.item = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

    }

}
