//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.13 at 07:58:15 PM MSK 
//


package ch.iec._61850._2003.scl;

import org.jvnet.jaxb2_commons.lang.*;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSubEquipment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSubEquipment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tPowerSystemResource">
 *       &lt;attGroup ref="{http://www.iec.ch/61850/2003/SCL}agVirtual"/>
 *       &lt;attribute name="phase" type="{http://www.iec.ch/61850/2003/SCL}tPhaseEnum" default="none" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSubEquipment")
@Entity(name = "TSubEquipment")
@Table(name = "TSUB_EQUIPMENT")
public class TSubEquipment
    extends TPowerSystemResource
    implements Equals, HashCode
{

    @XmlAttribute(name = "phase")
    protected TPhaseEnum phase;
    @XmlAttribute(name = "virtual")
    protected Boolean virtual;

    /**
     * Gets the value of the phase property.
     * 
     * @return
     *     possible object is
     *     {@link TPhaseEnum }
     *     
     */
    @Basic
    @Column(name = "PHASE", length = 255)
    @Enumerated(EnumType.STRING)
    public TPhaseEnum getPhase() {
        if (phase == null) {
            return TPhaseEnum.NONE;
        } else {
            return phase;
        }
    }

    /**
     * Sets the value of the phase property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPhaseEnum }
     *     
     */
    public void setPhase(TPhaseEnum value) {
        this.phase = value;
    }

    /**
     * Gets the value of the virtual property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Basic
    @Column(name = "VIRTUAL")
    public boolean isVirtual() {
        if (virtual == null) {
            return false;
        } else {
            return virtual;
        }
    }

    /**
     * Sets the value of the virtual property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVirtual(Boolean value) {
        this.virtual = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TSubEquipment)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TSubEquipment that = ((TSubEquipment) object);
        {
            TPhaseEnum lhsPhase;
            lhsPhase = this.getPhase();
            TPhaseEnum rhsPhase;
            rhsPhase = that.getPhase();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "phase", lhsPhase), LocatorUtils.property(thatLocator, "phase", rhsPhase), lhsPhase, rhsPhase)) {
                return false;
            }
        }
        {
            boolean lhsVirtual;
            lhsVirtual = ((this.virtual!= null)?this.isVirtual():false);
            boolean rhsVirtual;
            rhsVirtual = ((that.virtual!= null)?that.isVirtual():false);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "virtual", lhsVirtual), LocatorUtils.property(thatLocator, "virtual", rhsVirtual), lhsVirtual, rhsVirtual)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            TPhaseEnum thePhase;
            thePhase = this.getPhase();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "phase", thePhase), currentHashCode, thePhase);
        }
        {
            boolean theVirtual;
            theVirtual = ((this.virtual!= null)?this.isVirtual():false);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "virtual", theVirtual), currentHashCode, theVirtual);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
