//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.13 at 07:58:15 PM MSK 
//


package ch.iec._61850._2003.scl;

import org.jvnet.jaxb2_commons.lang.*;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for tVoltageLevel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tVoltageLevel">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tEquipmentContainer">
 *       &lt;sequence>
 *         &lt;element name="Voltage" type="{http://www.iec.ch/61850/2003/SCL}tVoltage" minOccurs="0"/>
 *         &lt;element name="Bay" type="{http://www.iec.ch/61850/2003/SCL}tBay" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tVoltageLevel", propOrder = {
    "voltage",
    "bay"
})
@Entity(name = "TVoltageLevel")
@Table(name = "TVOLTAGE_LEVEL")
public class TVoltageLevel
    extends TEquipmentContainer
    implements Equals, HashCode
{

    @XmlElement(name = "Voltage")
    protected TVoltage voltage;
    @XmlElement(name = "Bay", required = true)
    protected List<TBay> bay;

    /**
     * Gets the value of the voltage property.
     * 
     * @return
     *     possible object is
     *     {@link TVoltage }
     *     
     */
    @ManyToOne(targetEntity = TVoltage.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "VOLTAGE_TVOLTAGE_LEVEL_HJID")
    public TVoltage getVoltage() {
        return voltage;
    }

    /**
     * Sets the value of the voltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVoltage }
     *     
     */
    public void setVoltage(TVoltage value) {
        this.voltage = value;
    }

    /**
     * Gets the value of the bay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TBay }
     * 
     * 
     */
    @OneToMany(targetEntity = TBay.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "BAY_TVOLTAGE_LEVEL_HJID")
    public List<TBay> getBay() {
        if (bay == null) {
            bay = new ArrayList<TBay>();
        }
        return this.bay;
    }

    /**
     * 
     * 
     */
    public void setBay(List<TBay> bay) {
        this.bay = bay;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TVoltageLevel)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final TVoltageLevel that = ((TVoltageLevel) object);
        {
            TVoltage lhsVoltage;
            lhsVoltage = this.getVoltage();
            TVoltage rhsVoltage;
            rhsVoltage = that.getVoltage();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "voltage", lhsVoltage), LocatorUtils.property(thatLocator, "voltage", rhsVoltage), lhsVoltage, rhsVoltage)) {
                return false;
            }
        }
        {
            List<TBay> lhsBay;
            lhsBay = (((this.bay!= null)&&(!this.bay.isEmpty()))?this.getBay():null);
            List<TBay> rhsBay;
            rhsBay = (((that.bay!= null)&&(!that.bay.isEmpty()))?that.getBay():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "bay", lhsBay), LocatorUtils.property(thatLocator, "bay", rhsBay), lhsBay, rhsBay)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            TVoltage theVoltage;
            theVoltage = this.getVoltage();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "voltage", theVoltage), currentHashCode, theVoltage);
        }
        {
            List<TBay> theBay;
            theBay = (((this.bay!= null)&&(!this.bay.isEmpty()))?this.getBay():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "bay", theBay), currentHashCode, theBay);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
